// vue/components/application-ui/layout/list-containers/simple_with_dividers.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <ul class="divide-y divide-gray-200">
    <li v-for="item in items" :key="item.id" class="py-4">
      <!-- Your content -->
    </li>
  </ul>
</template>

<script>
const items = [
  { id: 1 },
  // More items...
]

export default {
  setup() {
    return {
      items,
    }
  },
}
</script>

// react/components/application-ui/layout/list-containers/simple_with_dividers.jsx
/* This example requires Tailwind CSS v2.0+ */
const items = [
  { id: 1 },
  // More items...
]

export default function Example() {
  return (
    <ul className="divide-y divide-gray-200">
      {items.map((item) => (
        <li key={item.id} className="py-4">
          {/* Your content */}
        </li>
      ))}
    </ul>
  )
}
