// react/components/application-ui/layout/list-containers/separate_cards.jsx
/* This example requires Tailwind CSS v2.0+ */
const items = [
  { id: 1 },
  // More items...
]

export default function Example() {
  return (
    <ul className="space-y-3">
      {items.map((item) => (
        <li key={item.id} className="bg-white shadow overflow-hidden rounded-md px-6 py-4">
          {/* Your content */}
        </li>
      ))}
    </ul>
  )
}

// vue/components/application-ui/layout/list-containers/separate_cards.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <ul class="space-y-3">
    <li v-for="item in items" :key="item.id" class="bg-white shadow overflow-hidden rounded-md px-6 py-4">
      <!-- Your content -->
    </li>
  </ul>
</template>

<script>
const items = [
  { id: 1 },
  // More items...
]

export default {
  setup() {
    return {
      items,
    }
  },
}
</script>
